// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHWjQZNgto3shfm-znC8dx0owATJtLMgw',
    appId: '1:307279963968:web:bd3fc4198ab84b88b23ca5',
    messagingSenderId: '307279963968',
    projectId: 'controle-financeio',
    authDomain: 'controle-financeio.firebaseapp.com',
    storageBucket: 'controle-financeio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXywLgXP6HpKOlVyq6VjZHJPm-Up-OpME',
    appId: '1:307279963968:android:90c80b9a4821e098b23ca5',
    messagingSenderId: '307279963968',
    projectId: 'controle-financeio',
    storageBucket: 'controle-financeio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcW4_O4D_B3asd7JyQ84Z_8bcGzW6MW9w',
    appId: '1:307279963968:ios:fdaae325b6d748b1b23ca5',
    messagingSenderId: '307279963968',
    projectId: 'controle-financeio',
    storageBucket: 'controle-financeio.firebasestorage.app',
    iosBundleId: 'controle.financeiro.com.br.controleFinanceiro',
  );
}
